org.gradle.jvmargs=-Xmx4G

# Mod Properties
modVersion=1.2.0

# Dependencies
fabricApiVersion=0.155.3
modmenuVersion=18.0.1
midnightlibVersion=1.9.3+26.1

# Minecraft Properties
minecraftVersion=26.1.2

# Fabric Properties
fabricLoaderVersion=0.19.3
fabricMinecraftVersionRange=>=26.1

# NeoForge Properties
neoforgeVersion=26.1.2.109
neoforgeLoaderRange=[26.1.2,)
neoforgeMinecraftVersionRange=[26.1.2]